name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

jobs:
  build_packages:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3.0.1
        with:
          dotnet-version: '6.0.x'
      - name: Test
        run: |
          dotnet restore &&
          dotnet build -c release -v q
