name: NuGet

on: workflow_dispatch

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  MAYORNUMBER: 1
  MINORNUMBER: 0

jobs:
  build-nuget:
    name: Build and publish nuget package
    strategy:
      matrix:
        project: [ 
          "src/WildStrategies.FileManager.Core", 
          "src/WildStrategies.FileManager.Azure", 
          "src/WildStrategies.FileManager.AWSS3" 
        ]
        
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3.2.0
        with:
          dotnet-version: '6.0.x'
          source-url: https://nuget.pkg.github.com/wildstrategies/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Nuget restore
        run: dotnet restore
      - name: Pack
        run: |
          dotnet pack --configuration=release \
            --include-symbols \
            --include-source \
            -o ./artifacts \
            -p:MayorNumber=${MAYORNUMBER:=1} \
            -p:MinorNumber=${MINORNUMBER:=0} \
            -p:BuildNumber=${GITHUB_RUN_NUMBER:=0} \
            -p:RevisionNumber=${REVISIONNUMBER:=0} \
            ${{ matrix.project }}
      - name: Publish
        run: |
          rm -f ./artifacts/*.symbols.nupkg
          for package in ./artifacts/*.nupkg; do dotnet nuget push $package; done
